# Generated by Django 2.2 on 2019-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190706_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
