# Generated by Django 2.2 on 2019-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20190708_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activate_type',
        ),
        migrations.RemoveField(
            model_name='studentcard',
            name='in_use',
        ),
        migrations.AddField(
            model_name='course',
            name='course_status_type',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='active_status_type',
            field=models.CharField(choices=[(0, 'inactive'), (1, 'active'), (2, 'blocked'), (9, 'banned')], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='studentcard',
            name='in_use_status',
            field=models.IntegerField(choices=[(0, 'not inuse'), (1, 'inuse'), (9, 'Expired')], default=0),
        ),
    ]
